export * from "./Footer/Footer";
export * from "./Header/Header";
export * from "./HomeOrders/HomeOrders";
export * from "./ContainerSwiper/ContainerSwiper";
export * from "./SwitchOrdesrs/SwitchOption";
export * from "./ListOrders/ListOrders";
export * from "./TitlePage/TitlePage";
export * from "./ItemImgSwiper/ItemImgSwiper";
export * from "./ServicesList/ServicesList";
export * from "./ListTasks/ListTasks";
export * from "./ListTasks/ItemTasks";
export * from './ListLvl/ListLvl'
export * from './ProgressBar/ProgressBar'
export * from './ListLvl/ItemLvl'
